// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v5.26.1
// source: proto/init/init.proto

package init

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src  string           `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest string           `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	Body *InitRequestBody `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_init_init_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_init_init_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_proto_init_init_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *InitRequest) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *InitRequest) GetBody() *InitRequestBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type InitRequestBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	NodeId  string   `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeIds []string `protobuf:"bytes,3,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
}

func (x *InitRequestBody) Reset() {
	*x = InitRequestBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_init_init_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequestBody) ProtoMessage() {}

func (x *InitRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_init_init_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequestBody.ProtoReflect.Descriptor instead.
func (*InitRequestBody) Descriptor() ([]byte, []int) {
	return file_proto_init_init_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequestBody) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InitRequestBody) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *InitRequestBody) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src  string            `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest string            `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	Body *InitResponseBody `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_init_init_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_init_init_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_proto_init_init_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *InitResponse) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *InitResponse) GetBody() *InitResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type InitResponseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId     int32   `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	InReplyTo *string `protobuf:"bytes,2,opt,name=in_reply_to,json=inReplyTo,proto3,oneof" json:"in_reply_to,omitempty"`
	Type      string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *InitResponseBody) Reset() {
	*x = InitResponseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_init_init_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponseBody) ProtoMessage() {}

func (x *InitResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_init_init_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponseBody.ProtoReflect.Descriptor instead.
func (*InitResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_init_init_proto_rawDescGZIP(), []int{3}
}

func (x *InitResponseBody) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *InitResponseBody) GetInReplyTo() string {
	if x != nil && x.InReplyTo != nil {
		return *x.InReplyTo
	}
	return ""
}

func (x *InitResponseBody) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SetBinaryNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BinaryName string `protobuf:"bytes,1,opt,name=binary_name,json=binaryName,proto3" json:"binary_name,omitempty"`
}

func (x *SetBinaryNameRequest) Reset() {
	*x = SetBinaryNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_init_init_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBinaryNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBinaryNameRequest) ProtoMessage() {}

func (x *SetBinaryNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_init_init_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBinaryNameRequest.ProtoReflect.Descriptor instead.
func (*SetBinaryNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_init_init_proto_rawDescGZIP(), []int{4}
}

func (x *SetBinaryNameRequest) GetBinaryName() string {
	if x != nil {
		return x.BinaryName
	}
	return ""
}

type SetBinaryNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetBinaryNameResponse) Reset() {
	*x = SetBinaryNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_init_init_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBinaryNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBinaryNameResponse) ProtoMessage() {}

func (x *SetBinaryNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_init_init_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBinaryNameResponse.ProtoReflect.Descriptor instead.
func (*SetBinaryNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_init_init_proto_rawDescGZIP(), []int{5}
}

var File_proto_init_init_proto protoreflect.FileDescriptor

var file_proto_init_init_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x69, 0x74, 0x2f, 0x69, 0x6e, 0x69,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6d, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x22, 0x68, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x79, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x22, 0x59, 0x0a, 0x0f, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x42, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x73, 0x22, 0x6a, 0x0a, 0x0c,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65,
	0x73, 0x74, 0x12, 0x34, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x6d, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x69,
	0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f,
	0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x72, 0x0a, 0x10, 0x49, 0x6e, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x15, 0x0a, 0x06,
	0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x73,
	0x67, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0b, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f,
	0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x69, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x54, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0e, 0x0a, 0x0c,
	0x5f, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x14,
	0x53, 0x65, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x42, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb2,
	0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45,
	0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x1b, 0x2e, 0x6d, 0x79, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x79, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x42, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x2e, 0x6d, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6d,
	0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x53, 0x65,
	0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x69,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_init_init_proto_rawDescOnce sync.Once
	file_proto_init_init_proto_rawDescData = file_proto_init_init_proto_rawDesc
)

func file_proto_init_init_proto_rawDescGZIP() []byte {
	file_proto_init_init_proto_rawDescOnce.Do(func() {
		file_proto_init_init_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_init_init_proto_rawDescData)
	})
	return file_proto_init_init_proto_rawDescData
}

var file_proto_init_init_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_init_init_proto_goTypes = []interface{}{
	(*InitRequest)(nil),           // 0: myservice.init.InitRequest
	(*InitRequestBody)(nil),       // 1: myservice.init.InitRequestBody
	(*InitResponse)(nil),          // 2: myservice.init.InitResponse
	(*InitResponseBody)(nil),      // 3: myservice.init.InitResponseBody
	(*SetBinaryNameRequest)(nil),  // 4: myservice.init.SetBinaryNameRequest
	(*SetBinaryNameResponse)(nil), // 5: myservice.init.SetBinaryNameResponse
}
var file_proto_init_init_proto_depIdxs = []int32{
	1, // 0: myservice.init.InitRequest.body:type_name -> myservice.init.InitRequestBody
	3, // 1: myservice.init.InitResponse.body:type_name -> myservice.init.InitResponseBody
	0, // 2: myservice.init.InitService.SendInit:input_type -> myservice.init.InitRequest
	4, // 3: myservice.init.InitService.SetBinaryName:input_type -> myservice.init.SetBinaryNameRequest
	2, // 4: myservice.init.InitService.SendInit:output_type -> myservice.init.InitResponse
	5, // 5: myservice.init.InitService.SetBinaryName:output_type -> myservice.init.SetBinaryNameResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_init_init_proto_init() }
func file_proto_init_init_proto_init() {
	if File_proto_init_init_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_init_init_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_init_init_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRequestBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_init_init_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_init_init_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitResponseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_init_init_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBinaryNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_init_init_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBinaryNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_init_init_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_init_init_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_init_init_proto_goTypes,
		DependencyIndexes: file_proto_init_init_proto_depIdxs,
		MessageInfos:      file_proto_init_init_proto_msgTypes,
	}.Build()
	File_proto_init_init_proto = out.File
	file_proto_init_init_proto_rawDesc = nil
	file_proto_init_init_proto_goTypes = nil
	file_proto_init_init_proto_depIdxs = nil
}
