// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v5.26.1
// source: proto/unique_ids/unique_ids.proto

package unique_ids

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UniqueIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src  string                `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest string                `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	Body *UniqueIdsRequestBody `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *UniqueIdsRequest) Reset() {
	*x = UniqueIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_unique_ids_unique_ids_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniqueIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueIdsRequest) ProtoMessage() {}

func (x *UniqueIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_unique_ids_unique_ids_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueIdsRequest.ProtoReflect.Descriptor instead.
func (*UniqueIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_unique_ids_unique_ids_proto_rawDescGZIP(), []int{0}
}

func (x *UniqueIdsRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *UniqueIdsRequest) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *UniqueIdsRequest) GetBody() *UniqueIdsRequestBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type UniqueIdsRequestBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *UniqueIdsRequestBody) Reset() {
	*x = UniqueIdsRequestBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_unique_ids_unique_ids_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniqueIdsRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueIdsRequestBody) ProtoMessage() {}

func (x *UniqueIdsRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_unique_ids_unique_ids_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueIdsRequestBody.ProtoReflect.Descriptor instead.
func (*UniqueIdsRequestBody) Descriptor() ([]byte, []int) {
	return file_proto_unique_ids_unique_ids_proto_rawDescGZIP(), []int{1}
}

func (x *UniqueIdsRequestBody) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UniqueIdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src  string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest string                 `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	Body *UniqueIdsResponseBody `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *UniqueIdsResponse) Reset() {
	*x = UniqueIdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_unique_ids_unique_ids_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniqueIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueIdsResponse) ProtoMessage() {}

func (x *UniqueIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_unique_ids_unique_ids_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueIdsResponse.ProtoReflect.Descriptor instead.
func (*UniqueIdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_unique_ids_unique_ids_proto_rawDescGZIP(), []int{2}
}

func (x *UniqueIdsResponse) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *UniqueIdsResponse) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *UniqueIdsResponse) GetBody() *UniqueIdsResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type UniqueIdsResponseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id   int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UniqueIdsResponseBody) Reset() {
	*x = UniqueIdsResponseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_unique_ids_unique_ids_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniqueIdsResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueIdsResponseBody) ProtoMessage() {}

func (x *UniqueIdsResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_unique_ids_unique_ids_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueIdsResponseBody.ProtoReflect.Descriptor instead.
func (*UniqueIdsResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_unique_ids_unique_ids_proto_rawDescGZIP(), []int{3}
}

func (x *UniqueIdsResponseBody) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UniqueIdsResponseBody) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_unique_ids_unique_ids_proto protoreflect.FileDescriptor

var file_proto_unique_ids_unique_ids_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69,
	0x64, 0x73, 0x2f, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6d, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69,
	0x6e, 0x69, 0x74, 0x22, 0x72, 0x0a, 0x10, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x79,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x55, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64,
	0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x2a, 0x0a, 0x14, 0x55, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x74, 0x0a, 0x11, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x39,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d,
	0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x55, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x3b, 0x0a, 0x15, 0x55, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x32, 0x68, 0x0a, 0x10, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x49, 0x64, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0d, 0x53, 0x65,
	0x6e, 0x64, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x73, 0x12, 0x20, 0x2e, 0x6d, 0x79,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x55, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x6d, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x12, 0x5a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x5f, 0x69, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_unique_ids_unique_ids_proto_rawDescOnce sync.Once
	file_proto_unique_ids_unique_ids_proto_rawDescData = file_proto_unique_ids_unique_ids_proto_rawDesc
)

func file_proto_unique_ids_unique_ids_proto_rawDescGZIP() []byte {
	file_proto_unique_ids_unique_ids_proto_rawDescOnce.Do(func() {
		file_proto_unique_ids_unique_ids_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_unique_ids_unique_ids_proto_rawDescData)
	})
	return file_proto_unique_ids_unique_ids_proto_rawDescData
}

var file_proto_unique_ids_unique_ids_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_unique_ids_unique_ids_proto_goTypes = []interface{}{
	(*UniqueIdsRequest)(nil),      // 0: myservice.init.UniqueIdsRequest
	(*UniqueIdsRequestBody)(nil),  // 1: myservice.init.UniqueIdsRequestBody
	(*UniqueIdsResponse)(nil),     // 2: myservice.init.UniqueIdsResponse
	(*UniqueIdsResponseBody)(nil), // 3: myservice.init.UniqueIdsResponseBody
}
var file_proto_unique_ids_unique_ids_proto_depIdxs = []int32{
	1, // 0: myservice.init.UniqueIdsRequest.body:type_name -> myservice.init.UniqueIdsRequestBody
	3, // 1: myservice.init.UniqueIdsResponse.body:type_name -> myservice.init.UniqueIdsResponseBody
	0, // 2: myservice.init.UniqueIdsService.SendUniqueIds:input_type -> myservice.init.UniqueIdsRequest
	2, // 3: myservice.init.UniqueIdsService.SendUniqueIds:output_type -> myservice.init.UniqueIdsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_unique_ids_unique_ids_proto_init() }
func file_proto_unique_ids_unique_ids_proto_init() {
	if File_proto_unique_ids_unique_ids_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_unique_ids_unique_ids_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniqueIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_unique_ids_unique_ids_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniqueIdsRequestBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_unique_ids_unique_ids_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniqueIdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_unique_ids_unique_ids_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniqueIdsResponseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_unique_ids_unique_ids_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_unique_ids_unique_ids_proto_goTypes,
		DependencyIndexes: file_proto_unique_ids_unique_ids_proto_depIdxs,
		MessageInfos:      file_proto_unique_ids_unique_ids_proto_msgTypes,
	}.Build()
	File_proto_unique_ids_unique_ids_proto = out.File
	file_proto_unique_ids_unique_ids_proto_rawDesc = nil
	file_proto_unique_ids_unique_ids_proto_goTypes = nil
	file_proto_unique_ids_unique_ids_proto_depIdxs = nil
}
